//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codeathon.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChallengeResult
    {
        public int Id { get; set; }
        public string SourceCode { get; set; }
        public string ExecuteTime { get; set; }
    
        public virtual PLanguage PLanguage { get; set; }
        public virtual User User { get; set; }
        public virtual Challenge Challenge { get; set; }
    }
}
