//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codeathon.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CodeathonContainer : DbContext
    {
        public CodeathonContainer()
            : base("name=CodeathonContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Challenge> Challenges { get; set; }
        public virtual DbSet<TestCase> TestCases { get; set; }
        public virtual DbSet<ChallengeResult> ChallengeResults { get; set; }
        public virtual DbSet<PLanguage> PLanguages { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Competition> Competitions { get; set; }
        public virtual DbSet<CompetitionChallenge> CompetitionChallenges { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
    }
}
