//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codeathon.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionChallenge
    {
        public int Id { get; set; }
        public int Point { get; set; }
        public Nullable<int> PrerequisiteId { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual Challenge Challenge { get; set; }
    }
}
