//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codeathon.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolutionReview
    {
        public long Id { get; set; }
        public string ArtPoint { get; set; }
        public string AcademicPoint { get; set; }
    
        public virtual User Author { get; set; }
        public virtual Solution Solution { get; set; }
    }
}
